using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using ShopBL;
using ShopModel;

/*
    This Controller for Customer was autogenerated by utilizing aspnet-codegenerator tool
    (find url in notes)

    -To Start
    --Install tool first = dotnet tool install -g dotnet-aspnet-codegenerator
    ---Add package to api project = dotnet add package Microsoft.VisualStudio.Web.CodeGeneration.Design

    **Check notes for directions on creating a Controller.
*/


namespace ShopApi.Controllers
{
    [Route("api/[controller]")]
    [ApiController]
    public class CustomerController : ControllerBase
    {
        //Customer dependency injection
        private ICustomerBL _customerBL;
        public CustomerController(ICustomerBL p_customerBL)
        {
            _customerBL = p_customerBL;
        }
        //------------------------------------------------------
        
        // GET: api/Customer
        [HttpGet("GetAll")]
        public IActionResult GetAllCustomer()
        {
            try
            {
                return Ok(_customerBL.GetAllCustomer());
            }
            catch (SqlException)
            {
                //The Api iss responsible for sending the right resource and right status code
                //In this case, if it was unable to connect to the database, it'll give a 404 status code
                return NotFound();
            }
            
        }

        // GET: api/Customer/5
        [HttpGet("GetCustomerByName/{customerName}")]
        public IActionResult GetCustomerByName(string customerName)
        {
            try
            {
                return Ok(_customerBL.GetCustomerbyName(customerName));
            }
            catch (System.Exception)
            {
                return NotFound();
            }
        }

        // POST: api/Customer
        [HttpPost("AddCustomer")]
        public IActionResult Post([FromBody] Customer p_customer)
        {
            try
            {
                return Created("Successfully added", _customerBL.AddCustomer(p_customer));
            }
            catch (System.Exception ex)
            {
                
                return Conflict(ex.Message);
            }
        }

        // PUT: api/Customer/5
        [HttpPut("Update{customerID}")]
        public IActionResult Put(int id, [FromBody] Customer p_customer)
        {
            try
            {
                return Ok(_customerBL.UpdateCustomer(p_customer));
            }
            catch (System.Exception ex)
            {
                return Conflict(ex.Message);
            }
        }

        // DELETE: api/Customer/5
        [HttpDelete("{id}")]
        public void Delete(int id)
        {
        }
    }
}
