using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Caching.Memory;
using ShopBL;
using ShopModel;

/*
    This Controller for Customer was autogenerated by utilizing aspnet-codegenerator tool
    (find url in notes)

    -To Start
    --Install tool first = dotnet tool install -g dotnet-aspnet-codegenerator
    ---Add package to api project = dotnet add package Microsoft.VisualStudio.Web.CodeGeneration.Design

    **Check notes for directions on creating a Controller.
*/


namespace ShopApi.Controllers
{
    [Route("api/[controller]")]
    [ApiController]
    public class CustomerController : ControllerBase
    {
        //Customer dependency injection
        private ICustomerBL _customerBL;

        private IMemoryCache _memoryCache;

        public CustomerController(ICustomerBL p_customerBL, IMemoryCache p_memoryCache)
        {
            _customerBL = p_customerBL;
            _memoryCache = p_memoryCache;
        }
        //------------------------------------------------------

        // GET: api/Customer
        [HttpGet("GetAllCustomer")]
        public async Task<IActionResult> GetAllCustomerAsync()
        {
            try
            {
                List<Customer> listofCustomer = new List<Customer>();
                //TryGetValue (check if the cache still exists and if it does "out listofCustomer" puts that data inside our variable)
                if (!_memoryCache.TryGetValue("CustomerList", out listofCustomer))
                {
                    listofCustomer = await _customerBL.GetAllCustomerAsync();
                    _memoryCache.Set("CustomerList", listofCustomer, new TimeSpan(0, 0, 30));
                }
                Log.Information("Successfully returned a list of all customers.");
                return Ok(listofCustomer);
            }
            catch (SqlException)
            {
                //The Api iss responsible for sending the right resource and right status code
                //In this case, if it was unable to connect to the database, it'll give a 404 status code
                Log.Warning("Could not find a list of customers.");
                return NotFound();
            }
            
        }

        // GET: api/Customer/4
        [HttpGet("SearchCustomerbyName")]
        public IActionResult GetCustomerByName([FromQuery] string customerName)
        {
            try
            {
                Log.Information("Successfully returned a customer by name.");
                return Ok(_customerBL.GetCustomerbyName(customerName));
            }
            catch (System.Exception)
            {
                return NotFound();
            }
        }

        // GET: api/Customer/5
        [HttpGet("SearchCustomerbyEmail")]
        public IActionResult GetCustomerByEmail([FromQuery] string customerEmail)
        {
            try
            {
                Log.Information("Successfully returned a customer by email.");
                return Ok(_customerBL.GetCustomerbyEmail(customerEmail));
            }
            catch (System.Exception)
            {
                Log.Warning("Issue updating inventory");
                return NotFound();
            }
        }

        // POST: api/Customer
        [HttpPost("AddCustomer")]
        public IActionResult AddCustomer([FromBody] Customer p_customer)
        {
            try
            {
                Log.Information("Successfully added a new customer.");
                return Created("Successfully added", _customerBL.AddCustomer(p_customer));
            }
            catch (System.Exception ex)
            {
                Log.Warning("Could not add a customer.");
                return Conflict(ex.Message);
            }
        }

        // PUT: api/Customer/5
        [HttpPut("UpdateCustomer{customerID}")]
        public IActionResult UpdateCustomer(int customerID, [FromBody] Customer p_customer)
        {
            try
            {
                Log.Information("Successfully updated customer information.");
                return Ok(_customerBL.UpdateCustomer(p_customer));
            }
            catch (System.Exception ex)
            {
                Log.Warning("Could not update customer information.");
                return Conflict(ex.Message);
            }
        }

        // GET: api/Customer/5
        [HttpGet("ViewOrderByCustomerID/{customerID}")]
        public IActionResult GetOrderbyCustomerID(int customerID)
        {
            try
            {
                Log.Information("Successfully returned a list or orders from a customer.");
                return Ok(_customerBL.GetOrderbyCustomerID(customerID));
            }
            catch (System.Exception ex)
            {
                Log.Warning("Could not view order history by customer ID.");
                return StatusCode(422, ex.Message);
            }
        }
    }
}
